name = "a0b_exti"
description = "A0B: EXTI API"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "exti"]

project-files = ["gnat/a0b_exti.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_base = "*"
a0b_callbacks = "*"
a0b_time = "*"
ada_synchronous_task_control = "*"
